apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dockerhub-ratelimit-exporter
spec:
  selector:
    matchLabels:
      app: dockerhub-ratelimit-exporter
  template:
    metadata:
      labels:
        app: dockerhub-ratelimit-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "26756"
    spec:
      containers:
        - env:
            - name: UPDATE_AGENT_NODE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          image: ghcr.io/dafnifacility/dockerhub-ratelimit-exporter:main
          imagePullPolicy: IfNotPresent
          name: exporter
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
          securityContext:
            runAsUser: 65532
            readOnlyRootFilesystem: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - containerPort: 55123
              name: http-prom
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
