apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - daemonset.yaml
  - monitor.yaml
  - rules.yaml
images:
  - name: ghcr.io/dafnifacility/dockerhub-ratelimit-exporter
    newTag: v0.1.0
