apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: update-engine-rules
spec:
  groups:
    - name: dhrl-monitoring
      rules:
        - alert: HostRunningOutOfDockerhubPulls
          annotations:
            description: Node {{$labels.node}} via {{ $labels.identity }} has less than 30% of its docker pulls remaining
            message: Consider using other registries
            severity_level: warning
          expr: |
            min(dockerhub_imagepull_remaining/dockerhub_imagepull_limit) by (node,identity)<0.3
          for: 5m
          labels:
            severity: warning
