apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: update-engine-rules
spec:
  groups:
    - name: dhrl-monitoring
      rules:
        - alert: HostRunningOutOfDockerhubPulls
          annotations:
            description: Node {{ $labels.node }} has less than 30% of its docker pulls remaining
            message: Consider using other registries
            severity_level: warning
          expr: |
            max(time()-flatcar_linux_update_engine_last_checked_time_s) by (node)>3600
          for: 1m
          labels:
            severity: warning
